# Generated by Django 3.0.7 on 2020-06-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='city',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='location',
            field=models.TextField(default=''),
        ),
    ]
