# Generated by Django 3.0.7 on 2020-06-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_info', '0002_auto_20200630_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
