# Generated by Django 3.0.7 on 2020-06-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_info', '0003_auto_20200630_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
